### PR TITLE
Fix display name persistence and add user profile management

### LINKED ISSUE #34: User Profiles
BUG: Every time a user logs in they get a new display name.

Instead of generating a display name for them let's just set the default display name to "Anonymous".

This also implies we need a profile page for users to update or set their display name. 

There should be a profile icon on the right side when a user logs in. It should be styled with DaisyUI and should have a generic person as the icon. When a user clicks it they should see a dropdown menu and a settings option. When the user goes to the settings page they should be able to set their display name.

NOTE: In the future we will allow them to update their profile picture.

### PR DESCRIPTION
**Pull request by mwoods79**
## Summary

This PR fixes the bug where users were getting new display names on every login and adds comprehensive user profile management functionality.

## Problem

Users were receiving new randomly-generated display names every time they logged in via magic link, which was confusing and prevented consistent identity across sessions.

## Solution

1. **Fixed the persistence bug** by removing \ from the \ in the sign_in_with_magic_link action
2. **Refactored display name generation** into a dedicated change module (\) that only generates names for new users
3. **Added profile management** features including:
   - Profile icon dropdown in navbar
   - Dedicated profile page at \
   - Form to update display name with validation
   - Theme toggle moved to dropdown as a logged-in user perk

## Implementation Details

- Created \ LiveView with authentication requirements
- Added \ action with proper validation (1-30 characters, non-empty)
- Integrated with AshPhoenix.Form for proper form handling
- Added comprehensive test coverage for all new features
- Followed existing patterns (e.g., change modules like \)

## Testing

- All existing tests pass
- Added new tests for profile functionality
- Manual testing confirms:
  - Display names persist across logins
  - Profile updates work correctly
  - Validation prevents invalid names
  - Flash messages display properly
  - Navbar updates immediately after profile changes

## Screenshots

Profile page with form:
Profile Page

Profile dropdown menu:
Profile Dropdown

Closes #34

### CODE REVIEW

File: lib/huddlz/accounts/user.ex [hunk 1]
```diff
@@ -136,6 +122,8 @@ defmodule Huddlz.Accounts.User do
     update :update_display_name do
       description "Update a user's display_name"
       accept [:display_name]
+
+      validate attribute_does_not_equal(:display_name, "")
```
Comment (mwoods79) [inline lib/huddlz/accounts/user.ex:126]: This validation should e between 3 and 30. Like what was planned.

File: lib/huddlz/accounts/user/changes/set_default_display_name.ex [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+  Only runs on create actions (specifically sign_in_with_magic_link which uses upsert).
+  """
+  use Ash.Resource.Change
+
+  @impl true
+  def change(changeset, _opts, _context) do
+    # Check if this is a new user (no id means it's an insert, not an update)
+    is_new_user = !changeset.data.id
+
+    if is_new_user and !Ash.Changeset.get_attribute(changeset, :display_name) do
```
Comment (mwoods79) [inline lib/huddlz/accounts/user/changes/set_default_display_name.ex:13]: if changeset.action_type == :create

File: lib/huddlz_web/components/layouts.ex [hunk 3]
```diff
@@ -15,27 +15,73 @@ defmodule HuddlzWeb.Layouts do
...
+                </span>
+              </li>
+              <li><a href="/profile">Profile</a></li>
+              <%= if Huddlz.Accounts.admin?(@current_user) do %>
+                <li><a href="/admin">Admin Panel</a></li>
+              <% end %>
+              <li class="mt-2"><a href="/sign-out">Sign Out</a></li>
+              <li class="px-2 py-2">
+                <div class="scale-75 origin-left">
+                  <.theme_toggle />
```
Comment (mwoods79) [inline lib/huddlz_web/components/layouts.ex:78]: Not sure I like this in the menu, I think we should move this to the profile page.

File: test/integration/magic_link_signup_test.exs [hunk 4]
```diff
@@ -37,20 +39,35 @@ defmodule Huddlz.Integration.MagicLinkSignupTest do
     assert_has(session, "h1", text: "Find your huddl")
   end
 
-  test "verify display name generation pattern", %{conn: _conn} do
-    # We're just testing the display name generation function directly
-    # Generate a display name using our function
-    display_name = User.generate_random_display_name()
+  test "verify display name generation module is configured correctly", %{conn: _conn} do
```
Comment (mwoods79) [inline test/integration/magic_link_signup_test.exs:42]: Doesn't need to verify the implementation, instead it needs to verify behavior. This test should just create a user and verify that a name was generated.

File: test/integration/magic_link_signup_test.exs [hunk 5]
```diff
@@ -37,20 +38,33 @@ defmodule Huddlz.Integration.MagicLinkSignupTest do
...
-    display_name = User.generate_random_display_name()
+  test "verify display name is generated for new users", %{conn: _conn} do
+    # Create a new user without providing a display name
+    email = "newuser#{System.unique_integer()}@example.com"
 
-    # Verify the display name follows our pattern
-    # It should be a combination of an adjective, animal, and number
-    assert String.match?(display_name, ~r/[A-Z][a-z]+[A-Z][a-z]+\d+/)
+    # Create an admin actor for the test
+    admin = Ash.Seed.seed!(User, %{email: "admin@test.com", role: :admin})
```
Comment (mwoods79) [inline test/integration/magic_link_signup_test.exs:46]: We should be using the generators to create users. It's a consistent interface that if we change it one place it changes everywhere.
